# Cargo config file.
# See: https://doc.rust-lang.org/cargo/reference/config.html

# Environments variables set for all `cargo ...` commands.
[env]

DEBUG="true"

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="cerium=debug,entity=debug,migration=info,api=debug"

## -- Database Url
DATABASE_URI="postgres://root:root@localhost:5433/orca"
SELENIUM_URI="http://localhost:4444/wd/hub/session"

STORAGE_BASE_URL = "http://localhost:9000"
STORAGE_ACCESS_KEY = "minioadmin"
STORAGE_ACCESS_SECRET = "minioadmin"

# -- Encryption salt used for JWT token and other secret keys
ENCRYPTION_SALT="strongencryption"

# use comma-seperated string to mention the CORS origin
ALLOWED_ORIGINS = "http://localhost:3000, http://localhost"


